### ISSUE TITLE
Cannot import name 'EncoderDecoderCache' from 'transformers'

### ISSUE THREAD

**Issue by keanshi-nlp** [Beckschen/LLaVolta#5]
When I was run the train-4stage.sh file in LLaVolta's repo, I found it report the error Cannot import name `'EncoderDecoderCache' from 'transformers'`. Since there no solution from the Internet, anyone can help me?

The traceback is like:
```bash
Traceback (most recent call last):
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/transformers/trainer.py", line 190, in <module>
    from peft import PeftModel
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/peft/mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/peft/mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/transformers/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data/shika/LLaVolta/llava/train/train_mem.py", line 1, in <module>
    from train import train
  File "/home/data/shika/LLaVolta/llava/train/train.py", line 32, in <module>
    from llava.train.llava_trainer import LLaVATrainer
  File "/home/data/shika/LLaVolta/llava/train/llava_trainer.py", line 7, in <module>
    from transformers import Trainer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (/home/data/shika/miniconda3/envs/llavolta/lib/python3.10/site-packages/transformers/__init__.py)
```

**Comment by JWGuo330** [comment]
I have the same question
` python web_demo.py
/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:411: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, qweight, scales, qzeros, g_idx, bits, maxq):
/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:419: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:461: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/qwen-7b/Qwen-7B/web_demo.py", line 213, in <module>
    main()
  File "/home/user/anaconda3/envs/qwen-7b/Qwen-7B/web_demo.py", line 207, in main
    model, tokenizer, config = _load_model_tokenizer(args)
  File "/home/user/anaconda3/envs/qwen-7b/Qwen-7B/web_demo.py", line 54, in _load_model_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3159, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 43, in <module>
    from auto_gptq import exllama_set_max_input_length
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/auto_gptq/__init__.py", line 3, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/auto_gptq/utils/peft_utils.py", line 6, in <module>
    from peft import PeftConfig, PeftModel, PeftType, get_peft_model
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/peft/mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/peft/mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/home/user/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/transformers/__init__.py)
`

**Comment by feiyu12138** [comment]
Hi,

Thank you for pointing this out! I overlooked the version note for peft. Please try using peft==0.10.0, as this is the version we are using. If you encounter any further issues, please don't hesitate to reach out.

Luoxin

**Comment by keanshi-nlp** [comment]
Thanks for the author's reply. I had solved it by using peft==0.14.0 and transformers==4.37.2, and any of other versions may cause problems on my server. Since there are differences between servers, the version of the two packages may depend on your system, cuda, etc.
